In [5]:
import numpy as np


In [4]:
a=[1,2,5,10,11]
b=np.argmax(a)
print(b)

4


In [5]:
print(a[np.argmax(a)])

11


In [6]:
a=[[6,8],
   [9,10]]
b=a[1][:]
print(b)

[9, 10]


In [7]:
def q():
    ss=10
    return ss

f=q()
print(f)



10


In [8]:
e=np.empty(shape=(2,2))
print(e)

[[1.43215639e-316 6.90242791e-310]
 [0.00000000e+000 0.00000000e+000]]


In [9]:
c = [None]*10
c[5]=2.2
print(c)

[None, None, None, None, None, 2.2, None, None, None, None]


In [12]:
matrix = np.empty(shape=(2,5),dtype='object') 
matrix[0][0]=5
matrix[0][1]=5
matrix[0][2]=5
matrix[0][3]=5
matrix[0][4]=5
print(matrix) 

[[5 5 5 5 5]
 [None None None None None]]


In [13]:
r =matrix[:][0]
print(r)

[5 5 5 5 5]


In [14]:
for i in range(5):
    b=matrix[:][i]
    

IndexError: index 2 is out of bounds for axis 0 with size 2

In [32]:
np.random.rand(1)

array([0.02374521])

In [41]:
a=[2,1,5,4,8]
b=np.random.choice(a)
print(b)
print(a.index(b))

8
4


In [58]:
Q_t=[1,2,3,3,3]
print(Q_t.index(np.random.choice(Q_t)))

0


In [59]:
a=[12,15,17,41]
c=5
t=8
n=2
b=a+c*np.sqrt(t/n)
print(b)

[22. 25. 27. 51.]


In [61]:
np.log(1000)/900



0.007675283643313486

In [62]:
def kk():
    aa=5
    return aa

kk()
print(aa)

NameError: name 'aa' is not defined

In [11]:
zz=np.zeros((2, 2))
a=zz
b=zz+1
c=zz=2
d=zz+3
e=zz+4
f=np.empty(shape=(3,2),dtype='object')
f[0,0]=zz
f[0,1]=a
f[1,0]=b
f[1,1]=c
f[2,0]=d
f[2,1]=e

print(f[2,0])

5


In [24]:
a=[]*6
a=np.reshape(a,(3,2))
print(a)

ValueError: cannot reshape array of size 0 into shape (3,2)

In [37]:
np.sqrt((np.log(100))/1)

2.145966026289347

In [47]:
a=[[2],[3],[5],[4],[3],[1],[5],[5]]
a=a.np.reshape((4,2))

AttributeError: 'list' object has no attribute 'np'

In [55]:
np.random.rand()

0.32829065626050835